const starRailAssetBase = 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/'

export const starRailCharacterImages: Record<string, string> = {
  'acheron': `${starRailAssetBase}1308.png`,
  'aglaea': `${starRailAssetBase}1402.png`,
  'anaxa': `${starRailAssetBase}1405.png`,
  'argenti': `${starRailAssetBase}1302.png`,
  'ashveil': `${starRailAssetBase}1504.png`,
  'aventurine': `${starRailAssetBase}1304.png`,
  'aventurine - waveflair': `${starRailAssetBase}1513.png`,
  'black swan': `${starRailAssetBase}1307.png`,
  'blade': `${starRailAssetBase}1205.png`,
  'boothill': `${starRailAssetBase}1315.png`,
  'castorice': `${starRailAssetBase}1407.png`,
  'cerydra': `${starRailAssetBase}1412.png`,
  'cipher': `${starRailAssetBase}1406.png`,
  'cyrene': `${starRailAssetBase}1415.png`,
  'dan heng - imbibitor lunae': `${starRailAssetBase}1213.png`,
  'dan heng - permansor terrae': `${starRailAssetBase}1414.png`,
  'dr. ratio': `${starRailAssetBase}1305.png`,
  'evanescia': `${starRailAssetBase}1505.png`,
  'evernight': `${starRailAssetBase}1413.png`,
  'feixiao': `${starRailAssetBase}1220.png`,
  'firefly': `${starRailAssetBase}1310.png`,
  'fu xuan': `${starRailAssetBase}1208.png`,
  'fugue': `${starRailAssetBase}1225.png`,
  'himeko - nova': `${starRailAssetBase}1510.png`,
  'huohuo': `${starRailAssetBase}1217.png`,
  'hyacine': `${starRailAssetBase}1409.png`,
  'hysilens': `${starRailAssetBase}1410.png`,
  'jade': `${starRailAssetBase}1314.png`,
  'jiaoqiu': `${starRailAssetBase}1218.png`,
  'jing yuan': `${starRailAssetBase}1204.png`,
  'jingliu': `${starRailAssetBase}1212.png`,
  'kafka': `${starRailAssetBase}1005.png`,
  'lingsha': `${starRailAssetBase}1222.png`,
  'luocha': `${starRailAssetBase}1203.png`,
  'mortenax blade': `${starRailAssetBase}1507.png`,
  'mydei': `${starRailAssetBase}1404.png`,
  'phainon': `${starRailAssetBase}1408.png`,
  'rappa': `${starRailAssetBase}1317.png`,
  'robin': `${starRailAssetBase}1309.png`,
  'robin - summeretto': `${starRailAssetBase}1512.png`,
  'ruan mei': `${starRailAssetBase}1303.png`,
  'seele': `${starRailAssetBase}1102.png`,
  'silver wolf': `${starRailAssetBase}1006.png`,
  'silver wolf lv.999': `${starRailAssetBase}1506.png`,
  'sparkle': `${starRailAssetBase}1306.png`,
  'sparxie': `${starRailAssetBase}1501.png`,
  'sunday': `${starRailAssetBase}1313.png`,
  'the dahlia': `${starRailAssetBase}1321.png`,
  'the herta': `${starRailAssetBase}1401.png`,
  'topaz and numby': `${starRailAssetBase}1112.png`,
  'tribbie': `${starRailAssetBase}1403.png`,
  'yao guang': `${starRailAssetBase}1502.png`,
  'yunli': `${starRailAssetBase}1221.png`,
}

export const starRailRewardImages: Record<string, string> = {
  'adversarial': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20014.png',
  'amber': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20003.png',
  'arlan': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1008.png',
  'arrows': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20000.png',
  'asta': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1009.png',
  'chorus': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20005.png',
  'collapsing sky': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20002.png',
  'cornucopia': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20001.png',
  'dan heng': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1002.png',
  'darting arrow': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20007.png',
  'data bank': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20006.png',
  'defense': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20010.png',
  'fine fruit': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20008.png',
  'gallagher': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1301.png',
  'guinaifen': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1210.png',
  'hanya': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1215.png',
  'herta': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1013.png',
  'hidden shadow': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20018.png',
  'hook': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1109.png',
  'lingering tear': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20024.png',
  'loop': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20011.png',
  'luka': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1111.png',
  'lynx': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1110.png',
  'march 7th': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1001.png',
  'mediation': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20019.png',
  'meshing cogs': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20012.png',
  'misha': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1312.png',
  'moze': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1223.png',
  'multiplication': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20015.png',
  'mutual demise': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20016.png',
  'natasha': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1105.png',
  'passkey': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20013.png',
  'pela': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1106.png',
  'pioneering': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20017.png',
  'qingque': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1201.png',
  'reminiscence': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20022.png',
  'sagacity': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20020.png',
  'sampo': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1108.png',
  'serval': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1103.png',
  'shadowburn': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20021.png',
  'shattered home': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20009.png',
  'sneering': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20023.png',
  'sushang': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1206.png',
  'tingyun': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1202.png',
  'void': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/20004.png',
  'xueyi': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1214.png',
  'yukong': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/character/1207.png',
  'a dream scented in wheat': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21060.png',
  'a little getaway': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21066.png',
  'a secret vow': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21012.png',
  'after the charmony fall': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21045.png',
  'before the tutorial mission starts': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/22000.png',
  'boundless choreo': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21044.png',
  'carve the moon, weave the clouds': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21032.png',
  'concert for two': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21043.png',
  'dance! dance! dance!': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21018.png',
  'day one of my new life': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21002.png',
  'destiny\'s threads forewoven': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21039.png',
  'dream\'s montage': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21048.png',
  'dreamville adventure': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21036.png',
  'eyes of the prey': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21008.png',
  'fermata': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21022.png',
  'final victor': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21037.png',
  'flames afar': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21038.png',
  'fly into a pink tomorrow': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/22006.png',
  'for tomorrow\'s journey': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/22002.png',
  'geniuses\' greetings': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21051.png',
  'geniuses\' repose': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21020.png',
  'good night and sleep well': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21001.png',
  'hey, over here': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/22001.png',
  'holiday thermae escapade': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21061.png',
  'in pursuit of the wind': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21056.png',
  'indelible promise': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21042.png',
  'it\'s showtime': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21041.png',
  'journey, forever peaceful': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21053.png',
  'landau\'s choice': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21009.png',
  'make the world clamor': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21013.png',
  'memories of the past': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21004.png',
  'ninja record: sound hunt': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/22003.png',
  'nowhere to run': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21033.png',
  'only silence remains': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21003.png',
  'past and future': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21025.png',
  'perfect timing': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21014.png',
  'planetary rendezvous': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21011.png',
  'poised to bloom': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21046.png',
  'post-op conversation': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21000.png',
  'quid pro quo': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21021.png',
  'resolution shines as pearls of sweat': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21015.png',
  'return to darkness': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21031.png',
  'river flows in spring': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21024.png',
  'see you at the end': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21062.png',
  'shadowed by night': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21047.png',
  'shared feeling': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21007.png',
  'subscribe for more!': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21017.png',
  'sweat now, cry less': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21052.png',
  'swordplay': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21010.png',
  'the birth of the self': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21006.png',
  'the day the cosmos fell': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21040.png',
  'the flower remembers': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21057.png',
  'the forever victual': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/22005.png',
  'the great cosmic enterprise': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/22004.png',
  'the moles welcome you': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21005.png',
  'the seriousness of breakfast': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21027.png',
  'the story\'s next page': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21054.png',
  'this is me!': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21030.png',
  'today is another peaceful day': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21034.png',
  'trend of the universal market': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21016.png',
  'under the blue sky': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21019.png',
  'victory in a blink': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21050.png',
  'warmth shortens cold nights': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21028.png',
  'we are wildfire': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21023.png',
  'we will meet again': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21029.png',
  'what is real?': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21035.png',
  'woof! walk time!': 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/light_cone/21026.png',
}
