export type WuwaBannerRecord = {
  id: string
  version: string
  phase: number
  featuredName: string
  imageUrl: string
}

const characterAsset = (name: string) => `https://raw.githubusercontent.com/ryanbenson/wuthering-waves-assets/master/images/${name}.png`
const weaponAsset = (name: string) => `https://raw.githubusercontent.com/ryanbenson/wuthering-waves-assets/master/images/weapons/${name}.png`

export const wuwaCharacterRecords: WuwaBannerRecord[] = [
  { id: 'wuwa-character-1-0-p1-jiyan', version: '1.0', phase: 1, featuredName: 'Jiyan', imageUrl: characterAsset('Jiyan') },
  { id: 'wuwa-character-1-0-p2-yinlin', version: '1.0', phase: 2, featuredName: 'Yinlin', imageUrl: characterAsset('Yinlin') },
  { id: 'wuwa-character-1-1-p1-jinhsi', version: '1.1', phase: 1, featuredName: 'Jinhsi', imageUrl: characterAsset('Jinhsi') },
  { id: 'wuwa-character-1-1-p2-changli', version: '1.1', phase: 2, featuredName: 'Changli', imageUrl: characterAsset('Changli') },
  { id: 'wuwa-character-1-2-p1-zhezhi', version: '1.2', phase: 1, featuredName: 'Zhezhi', imageUrl: characterAsset('Zhezhi') },
  { id: 'wuwa-character-1-2-p2-xiangli-yao', version: '1.2', phase: 2, featuredName: 'Xiangli Yao', imageUrl: characterAsset('XiangliYao') },
  { id: 'wuwa-character-1-3-p1-shorekeeper', version: '1.3', phase: 1, featuredName: 'Shorekeeper', imageUrl: characterAsset('Shorekeeper') },
  { id: 'wuwa-character-1-3-p2-jiyan', version: '1.3', phase: 2, featuredName: 'Jiyan', imageUrl: characterAsset('Jiyan') },
  { id: 'wuwa-character-1-4-p1-camellya', version: '1.4', phase: 1, featuredName: 'Camellya', imageUrl: characterAsset('Camellya') },
  { id: 'wuwa-character-1-4-p2-yinlin', version: '1.4', phase: 2, featuredName: 'Yinlin', imageUrl: characterAsset('Yinlin') },
  { id: 'wuwa-character-2-0-p1-carlotta', version: '2.0', phase: 1, featuredName: 'Carlotta', imageUrl: characterAsset('Carlotta') },
  { id: 'wuwa-character-2-0-p2-roccia', version: '2.0', phase: 2, featuredName: 'Roccia', imageUrl: characterAsset('Roccia') },
  { id: 'wuwa-character-2-1-p1-phoebe', version: '2.1', phase: 1, featuredName: 'Phoebe', imageUrl: characterAsset('Phoebe') },
  { id: 'wuwa-character-2-1-p2-brant', version: '2.1', phase: 2, featuredName: 'Brant', imageUrl: characterAsset('Brant') },
  { id: 'wuwa-character-2-2-p1-cantarella', version: '2.2', phase: 1, featuredName: 'Cantarella', imageUrl: characterAsset('Cantarella') },
  { id: 'wuwa-character-2-2-p2-shorekeeper', version: '2.2', phase: 2, featuredName: 'Shorekeeper', imageUrl: characterAsset('Shorekeeper') },
  { id: 'wuwa-character-2-3-p1-zani', version: '2.3', phase: 1, featuredName: 'Zani', imageUrl: characterAsset('Zani') },
  { id: 'wuwa-character-2-3-p2-ciaccona', version: '2.3', phase: 2, featuredName: 'Ciaccona', imageUrl: characterAsset('Ciaccona') },
  { id: 'wuwa-character-2-4-p1-cartethyia', version: '2.4', phase: 1, featuredName: 'Cartethyia', imageUrl: characterAsset('Cartethyia') },
  { id: 'wuwa-character-2-4-p2-lupa', version: '2.4', phase: 2, featuredName: 'Lupa', imageUrl: characterAsset('Lupa') },
  { id: 'wuwa-character-2-5-p1-phrolova', version: '2.5', phase: 1, featuredName: 'Phrolova', imageUrl: characterAsset('Phrolova') },
  { id: 'wuwa-character-2-5-p2-cantarella', version: '2.5', phase: 2, featuredName: 'Cantarella', imageUrl: characterAsset('Cantarella') },
  { id: 'wuwa-character-2-6-p1-augusta', version: '2.6', phase: 1, featuredName: 'Augusta', imageUrl: characterAsset('Augusta') },
  { id: 'wuwa-character-2-6-p2-iuno', version: '2.6', phase: 2, featuredName: 'Iuno', imageUrl: characterAsset('Iuno') },
  { id: 'wuwa-character-2-7-p1-galbrena', version: '2.7', phase: 1, featuredName: 'Galbrena', imageUrl: characterAsset('Galbrena') },
  { id: 'wuwa-character-2-7-p2-qiuyuan', version: '2.7', phase: 2, featuredName: 'Qiuyuan', imageUrl: characterAsset('Qiuyuan') },
  { id: 'wuwa-character-2-8-p1-chisa', version: '2.8', phase: 1, featuredName: 'Chisa', imageUrl: characterAsset('Chisa') },
  { id: 'wuwa-character-2-8-p2-phrolova', version: '2.8', phase: 2, featuredName: 'Phrolova', imageUrl: characterAsset('Phrolova') },
  { id: 'wuwa-character-3-0-p1-lynae', version: '3.0', phase: 1, featuredName: 'Lynae', imageUrl: characterAsset('Lynae') },
  { id: 'wuwa-character-3-0-p2-mornye', version: '3.0', phase: 2, featuredName: 'Mornye', imageUrl: characterAsset('Mornye') },
  { id: 'wuwa-character-3-1-p1-aemeath', version: '3.1', phase: 1, featuredName: 'Aemeath', imageUrl: characterAsset('Aemeath') },
  { id: 'wuwa-character-3-2-p1-sigrika', version: '3.2', phase: 1, featuredName: 'Sigrika', imageUrl: characterAsset('Sigrika') },
  { id: 'wuwa-character-3-2-p2-lynae', version: '3.2', phase: 2, featuredName: 'Lynae', imageUrl: characterAsset('Lynae') },
  { id: 'wuwa-character-3-2-p2-zani', version: '3.2', phase: 2, featuredName: 'Zani', imageUrl: characterAsset('Zani') },
  { id: 'wuwa-character-3-2-p2-phoebe', version: '3.2', phase: 2, featuredName: 'Phoebe', imageUrl: characterAsset('Phoebe') },
  { id: 'wuwa-character-3-3-p1-hiyuki', version: '3.3', phase: 1, featuredName: 'Hiyuki', imageUrl: characterAsset('Hiyuki') },
  { id: 'wuwa-character-3-3-p1-mornye', version: '3.3', phase: 1, featuredName: 'Mornye', imageUrl: characterAsset('Mornye') },
  { id: 'wuwa-character-3-3-p1-iuno', version: '3.3', phase: 1, featuredName: 'Iuno', imageUrl: characterAsset('Iuno') },
  { id: 'wuwa-character-3-3-p2-denia', version: '3.3', phase: 2, featuredName: 'Denia', imageUrl: characterAsset('Denia') },
  { id: 'wuwa-character-3-3-p2-chisa', version: '3.3', phase: 2, featuredName: 'Chisa', imageUrl: characterAsset('Chisa') },
  { id: 'wuwa-character-3-3-p2-phrolova', version: '3.3', phase: 2, featuredName: 'Phrolova', imageUrl: characterAsset('Phrolova') },
  { id: 'wuwa-character-3-4-p1-lucy', version: '3.4', phase: 1, featuredName: 'Lucy', imageUrl: characterAsset('Lucy') },
  { id: 'wuwa-character-3-4-p1-rebecca', version: '3.4', phase: 1, featuredName: 'Rebecca', imageUrl: characterAsset('Rebecca') },
  { id: 'wuwa-character-3-4-p2-lucilla', version: '3.4', phase: 2, featuredName: 'Lucilla', imageUrl: characterAsset('Lucilla') },
  { id: 'wuwa-character-3-4-p2-cartethyia', version: '3.4', phase: 2, featuredName: 'Cartethyia', imageUrl: characterAsset('Cartethyia') },
  { id: 'wuwa-character-3-5-p1-suisui', version: '3.5', phase: 1, featuredName: 'Suisui', imageUrl: characterAsset('Suisui') },
  { id: 'wuwa-character-3-5-p1-aemeath', version: '3.5', phase: 1, featuredName: 'Aemeath', imageUrl: characterAsset('Aemeath') },
  { id: 'wuwa-character-3-6-p1-qingxiao', version: '3.6', phase: 1, featuredName: 'Qingxiao', imageUrl: characterAsset('Qingxiao') },
  { id: 'wuwa-character-3-6-p1-denia', version: '3.6', phase: 1, featuredName: 'Denia', imageUrl: characterAsset('Denia') },
  { id: 'wuwa-character-3-6-p2-jingran', version: '3.6', phase: 2, featuredName: 'Jingran', imageUrl: characterAsset('Jingran') },
  { id: 'wuwa-character-3-6-p2-hiyuki', version: '3.6', phase: 2, featuredName: 'Hiyuki', imageUrl: characterAsset('Hiyuki') },
  { id: 'wuwa-character-3-6-p2-mornye', version: '3.6', phase: 2, featuredName: 'Mornye', imageUrl: characterAsset('Mornye') },
]

export const wuwaWeaponRecords: WuwaBannerRecord[] = [
  { id: 'wuwa-weapon-1-0-p1-verdant-summit', version: '1.0', phase: 1, featuredName: 'Verdant Summit', imageUrl: weaponAsset('VerdantSummit') },
  { id: 'wuwa-weapon-1-0-p2-stringmaster', version: '1.0', phase: 2, featuredName: 'Stringmaster', imageUrl: weaponAsset('Stringmaster') },
  { id: 'wuwa-weapon-1-1-p1-ages-of-harvest', version: '1.1', phase: 1, featuredName: 'Ages of Harvest', imageUrl: weaponAsset('AgesOfHarvest') },
  { id: 'wuwa-weapon-1-1-p2-blazing-brilliance', version: '1.1', phase: 2, featuredName: 'Blazing Brilliance', imageUrl: weaponAsset('BlazingBrilliance') },
  { id: 'wuwa-weapon-1-2-p1-rime-draped-sprouts', version: '1.2', phase: 1, featuredName: 'Rime-Draped Sprouts', imageUrl: weaponAsset('RimeDrapedSprouts') },
  { id: 'wuwa-weapon-1-2-p2-veritys-handle', version: '1.2', phase: 2, featuredName: "Verity's Handle", imageUrl: weaponAsset('VeritysHandle') },
  { id: 'wuwa-weapon-1-3-p1-stellar-symphony', version: '1.3', phase: 1, featuredName: 'Stellar Symphony', imageUrl: weaponAsset('StellarSymphony') },
  { id: 'wuwa-weapon-1-4-p1-red-spring', version: '1.4', phase: 1, featuredName: 'Red Spring', imageUrl: weaponAsset('RedSpring') },
  { id: 'wuwa-weapon-2-0-p1-the-last-dance', version: '2.0', phase: 1, featuredName: 'The Last Dance', imageUrl: weaponAsset('TheLastDance') },
  { id: 'wuwa-weapon-2-0-p2-tragicomedy', version: '2.0', phase: 2, featuredName: 'Tragicomedy', imageUrl: weaponAsset('Tragicomedy') },
  { id: 'wuwa-weapon-2-6-p1-radiance-cleaver', version: '2.6', phase: 1, featuredName: 'Radiance Cleaver', imageUrl: weaponAsset('RadianceCleaver') },
  { id: 'wuwa-weapon-2-8-p1-spectrum-blaster', version: '2.8', phase: 1, featuredName: 'Spectrum Blaster', imageUrl: weaponAsset('SpectrumBlaster') },
  { id: 'wuwa-weapon-3-0-p1-spectrum-blaster', version: '3.0', phase: 1, featuredName: 'Spectrum Blaster', imageUrl: weaponAsset('SpectrumBlaster') },
  { id: 'wuwa-weapon-3-0-p2-starfield-calibrator', version: '3.0', phase: 2, featuredName: 'Starfield Calibrator', imageUrl: weaponAsset('StarfieldCalibrator') },
  { id: 'wuwa-weapon-3-1-p1-everbright-polestar', version: '3.1', phase: 1, featuredName: 'Everbright Polestar', imageUrl: weaponAsset('EverbrightPolestar') },
  { id: 'wuwa-weapon-3-2-p1-emerald-sentence', version: '3.2', phase: 1, featuredName: 'Emerald Sentence', imageUrl: weaponAsset('EmeraldSentence') },
  { id: 'wuwa-weapon-3-2-p2-solsworn-ciphers', version: '3.2', phase: 2, featuredName: 'Solsworn Ciphers', imageUrl: weaponAsset('SolswornCiphers') },
  { id: 'wuwa-weapon-3-3-p1-frostburn', version: '3.3', phase: 1, featuredName: 'Frostburn', imageUrl: weaponAsset('Frostburn') },
  { id: 'wuwa-weapon-3-3-p1-forged-dwarf-star', version: '3.3', phase: 1, featuredName: 'Forged Dwarf Star', imageUrl: weaponAsset('ForgedDwarfStar') },
  { id: 'wuwa-weapon-3-3-p2-moongazers-sigil', version: '3.3', phase: 2, featuredName: "Moongazer's Sigil", imageUrl: weaponAsset('MoongazersSigil') },
  { id: 'wuwa-weapon-3-3-p2-kumokiri', version: '3.3', phase: 2, featuredName: 'Kumokiri', imageUrl: weaponAsset('Kumokiri') },
  { id: 'wuwa-weapon-3-3-p2-lethean-elegy', version: '3.3', phase: 2, featuredName: 'Lethean Elegy', imageUrl: weaponAsset('LetheanElegy') },
  { id: 'wuwa-weapon-3-4-p1-spectral-trigger', version: '3.4', phase: 1, featuredName: 'Spectral Trigger', imageUrl: weaponAsset('SpectralTrigger') },
  { id: 'wuwa-weapon-3-4-p1-skull-thrasher', version: '3.4', phase: 1, featuredName: 'Skull Thrasher', imageUrl: weaponAsset('SkullThrasher') },
  { id: 'wuwa-weapon-3-5-p1-firstlights-herald', version: '3.5', phase: 1, featuredName: "Firstlight's Herald", imageUrl: weaponAsset('FirstlightsHerald') },
  { id: 'wuwa-weapon-3-5-p1-everbright-polestar', version: '3.5', phase: 1, featuredName: 'Everbright Polestar', imageUrl: weaponAsset('EverbrightPolestar') },
  { id: 'wuwa-weapon-3-6-p1-glint-of-clouds', version: '3.6', phase: 1, featuredName: 'Glint of Clouds', imageUrl: weaponAsset('GlintOfClouds') },
  { id: 'wuwa-weapon-3-6-p2-frostburn', version: '3.6', phase: 2, featuredName: 'Frostburn', imageUrl: weaponAsset('Frostburn') },
]
